# Generated by Django 4.2.4 on 2023-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_recipe_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True),
        ),
    ]
